#!/usr/bin/env bash
# Render non-secret, two-Scribe HA drill configurations for one real provider.
#
# This script intentionally does not contact the provider, copy credentials to
# a host, start Scripture, or invoke kubectl. It only turns locally supplied
# endpoint/bucket metadata into ignored YAML. A later operator-approved launch
# must supply the matching credential variables to each Scribe process.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<'EOF'
Usage:
  scripts/render-provider-scribe-drill.sh \
    --backend r2|s3 --run-id ID --a-host HOST --b-host HOST [--out-dir PATH]

Required environment for r2:
  R2_ENDPOINT R2_BUCKET R2_REGION
  (credential variables R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY are deliberately
   not read or written by this renderer.)

Required environment for s3:
  S3_ENDPOINT S3_BUCKET S3_REGION
  (the later launch needs AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY.)

The generated YAML contains endpoint and bucket metadata but never credentials.
It is written only under ignored config/local/ unless --out-dir names another
ignored config/local path.
EOF
}

backend=""
run_id=""
a_host=""
b_host=""
out_dir=""

while (($#)); do
  case "$1" in
    --backend) backend="${2:?--backend needs r2 or s3}"; shift 2 ;;
    --run-id) run_id="${2:?--run-id needs an id}"; shift 2 ;;
    --a-host) a_host="${2:?--a-host needs a host}"; shift 2 ;;
    --b-host) b_host="${2:?--b-host needs a host}"; shift 2 ;;
    --out-dir) out_dir="${2:?--out-dir needs a path}"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

[[ "$backend" == "r2" || "$backend" == "s3" ]] || {
  echo "--backend must be r2 or s3" >&2; exit 2;
}
[[ "$run_id" =~ ^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$ ]] || {
  echo "--run-id must be 1–64 ASCII letters, digits, dot, underscore, or hyphen" >&2
  exit 2
}
[[ -n "$a_host" && -n "$b_host" && "$a_host" != "$b_host" ]] || {
  echo "--a-host and --b-host must be distinct non-empty addresses" >&2
  exit 2
}

if [[ "$backend" == "r2" ]]; then
  endpoint="${R2_ENDPOINT:?R2_ENDPOINT is required}"
  bucket="${R2_BUCKET:?R2_BUCKET is required}"
  region="${R2_REGION:?R2_REGION is required}"
else
  endpoint="${S3_ENDPOINT:?S3_ENDPOINT is required}"
  bucket="${S3_BUCKET:?S3_BUCKET is required}"
  region="${S3_REGION:?S3_REGION is required}"
fi

if [[ -z "$out_dir" ]]; then
  out_dir="$repo_root/config/local/provider-scribe-drills/$backend-$run_id"
fi
case "$out_dir" in
  "$repo_root"/config/local/*) ;;
  *)
    echo "refuse output outside ignored config/local/: $out_dir" >&2
    exit 2
    ;;
esac
[[ ! -e "$out_dir" ]] || { echo "refuse to overwrite $out_dir" >&2; exit 2; }
mkdir -p "$out_dir"

prefix="scripture/submission/$backend/$run_id"
render() {
  local owner="$1" posture="$2" advertise="$3" bind="$4" output="$5"
  cat >"$output" <<EOF
# Generated by scripts/render-provider-scribe-drill.sh.
# Non-secret provider metadata only. Credentials come from the process env.
version: 1

node:
  owner_id: "$owner"
  advertise: "tcp://$advertise"

store:
  backend: $backend
  endpoint: "$endpoint"
  bucket: "$bucket"
  region: "$region"
  prefix: "$prefix"

ha:
  mode: serving-authority

metrics:
  status_bind: "127.0.0.1:9100"

scribe:
  limits:
    max_assignments: 1
    max_pending_bytes: 4194304
    max_pending_records: 1024
    max_concurrent_tasks: 64
  assignments:
    - id: submission
      canon: "submit-canon-001"
      verse: "submit-verse-001"
      cohort_id: "submit-cohort-01"
      writer_id: "submit-writer-01"
      posture: $posture
      advertise: "tcp://$advertise"
      ingress:
        bind: "$bind"
EOF
}

render "scripture-own-a!" "bootstrap-if-empty" "$a_host:19001" "$a_host:19001" "$out_dir/scribe-a.yaml"
render "scripture-own-b!" "standby" "$b_host:19001" "$b_host:19001" "$out_dir/scribe-b.yaml"

printf '%s\n' \
  "rendered=$out_dir" \
  "backend=$backend" \
  "prefix=$prefix" \
  "next=validate both YAML files, then use an operator-approved credential handoff"
